<?php
/**
 * AttributeDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Otto\Client;

/**
 * AttributeDefinitionTest Class Doc Comment
 *
 * @category    Class
 * @description AttributeDefinition
 * @package     Otto\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AttributeDefinitionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AttributeDefinition"
     */
    public function testAttributeDefinition()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "attribute_group"
     */
    public function testPropertyAttributeGroup()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "multi_value"
     */
    public function testPropertyMultiValue()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "unit_display_name"
     */
    public function testPropertyUnitDisplayName()
    {
    }

    /**
     * Test attribute "allowed_values"
     */
    public function testPropertyAllowedValues()
    {
    }

    /**
     * Test attribute "feature_relevance"
     */
    public function testPropertyFeatureRelevance()
    {
    }

    /**
     * Test attribute "related_media_assets"
     */
    public function testPropertyRelatedMediaAssets()
    {
    }

    /**
     * Test attribute "relevance"
     */
    public function testPropertyRelevance()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "example_values"
     */
    public function testPropertyExampleValues()
    {
    }

    /**
     * Test attribute "recommended_values"
     */
    public function testPropertyRecommendedValues()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }
}
