<?php
/**
 * AvailableQuantityRequestDTOV2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Available Quantity API
 *
 * Quantities interface
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Otto\Client;

/**
 * AvailableQuantityRequestDTOV2Test Class Doc Comment
 *
 * @category    Class
 * @description AvailableQuantityRequestDTOV2
 * @package     Otto\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AvailableQuantityRequestDTOV2Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AvailableQuantityRequestDTOV2"
     */
    public function testAvailableQuantityRequestDTOV2()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }
}
