<?php
/**
 * NormPriceInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Otto\Client;

/**
 * NormPriceInfoTest Class Doc Comment
 *
 * @category    Class
 * @description The information about normed prices, must be provided completely, or not at all. The representation of the normprice have to contain from the following values for normAmount and normUnit: 1 pcs,1 sqm,1 kg,1 l,1 m,100 ml,100 g,1 g,1000 g,1 pair,1 RM,1 dm3.
 * @package     Otto\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NormPriceInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NormPriceInfo"
     */
    public function testNormPriceInfo()
    {
    }

    /**
     * Test attribute "norm_amount"
     */
    public function testPropertyNormAmount()
    {
    }

    /**
     * Test attribute "norm_unit"
     */
    public function testPropertyNormUnit()
    {
    }

    /**
     * Test attribute "sales_amount"
     */
    public function testPropertySalesAmount()
    {
    }

    /**
     * Test attribute "sales_unit"
     */
    public function testPropertySalesUnit()
    {
    }
}
