<?php
/**
 * PositionItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders - version 3
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Otto\Client;

/**
 * PositionItemTest Class Doc Comment
 *
 * @category    Class
 * @description PositionItem
 * @package     Otto\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PositionItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PositionItem"
     */
    public function testPositionItem()
    {
    }

    /**
     * Test attribute "position_item_id"
     */
    public function testPropertyPositionItemId()
    {
    }

    /**
     * Test attribute "fulfillment_status"
     */
    public function testPropertyFulfillmentStatus()
    {
    }

    /**
     * Test attribute "item_value_gross_price"
     */
    public function testPropertyItemValueGrossPrice()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "tracking_info"
     */
    public function testPropertyTrackingInfo()
    {
    }

    /**
     * Test attribute "sent_date"
     */
    public function testPropertySentDate()
    {
    }

    /**
     * Test attribute "returned_date"
     */
    public function testPropertyReturnedDate()
    {
    }

    /**
     * Test attribute "cancellation_date"
     */
    public function testPropertyCancellationDate()
    {
    }
}
