<?php
/**
 * ProductDescriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Otto\Client;

/**
 * ProductDescriptionTest Class Doc Comment
 *
 * @category    Class
 * @description Extensive description of the product.
 * @package     Otto\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductDescriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductDescription"
     */
    public function testProductDescription()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {
    }

    /**
     * Test attribute "product_line"
     */
    public function testPropertyProductLine()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "production_date"
     */
    public function testPropertyProductionDate()
    {
    }

    /**
     * Test attribute "multi_pack"
     */
    public function testPropertyMultiPack()
    {
    }

    /**
     * Test attribute "bundle"
     */
    public function testPropertyBundle()
    {
    }

    /**
     * Test attribute "fsc_certified"
     */
    public function testPropertyFscCertified()
    {
    }

    /**
     * Test attribute "disposal"
     */
    public function testPropertyDisposal()
    {
    }

    /**
     * Test attribute "product_url"
     */
    public function testPropertyProductUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "bullet_points"
     */
    public function testPropertyBulletPoints()
    {
    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
    }
}
