<?php
/**
 * ProductVariationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Otto\Client;

/**
 * ProductVariationTest Class Doc Comment
 *
 * @category    Class
 * @description ProductVariation
 * @package     Otto\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductVariationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductVariation"
     */
    public function testProductVariation()
    {
    }

    /**
     * Test attribute "product_reference"
     */
    public function testPropertyProductReference()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "isbn"
     */
    public function testPropertyIsbn()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "pzn"
     */
    public function testPropertyPzn()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "moin"
     */
    public function testPropertyMoin()
    {
    }

    /**
     * Test attribute "offering_start_date"
     */
    public function testPropertyOfferingStartDate()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "max_order_quantity"
     */
    public function testPropertyMaxOrderQuantity()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "media_assets"
     */
    public function testPropertyMediaAssets()
    {
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
    }

    /**
     * Test attribute "pricing"
     */
    public function testPropertyPricing()
    {
    }

    /**
     * Test attribute "logistics"
     */
    public function testPropertyLogistics()
    {
    }
}
