<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Public Partner Product API
 *
 * Manage your product data, send images and                   much more.
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Otto\Client;

use Otto\Client\Configuration;
use Otto\Client\ApiException;
use Otto\Client\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrUpdateProductVariations
     *
     * Create or update your product variations and get a process-id to query results. The limit for the number of product variations in one request is 500..
     *
     */
    public function testCreateOrUpdateProductVariations()
    {
    }

    /**
     * Test case for failedByProcessId
     *
     * Request the failed products of the product data delivery with the linked processUuid. The response will contain a list of failed products with associated error details..
     *
     */
    public function testFailedByProcessId()
    {
    }

    /**
     * Test case for getPartnerProducts
     *
     * Read your product variations. The total number of results could be limited by specifying query parameters. Generally the resulting product variations will be paginated. The default page length is 100 product variations per response, also the page size limit. The links specified in the result can be used to page through the total result space..
     *
     */
    public function testGetPartnerProducts()
    {
    }

    /**
     * Test case for getProductVariation
     *
     * Read a single product variation..
     *
     */
    public function testGetProductVariation()
    {
    }

    /**
     * Test case for progressByProcessId
     *
     * Request the results of a product data delivery. The response will contain the links for the different parts of the result: products successfully created or updated, products with failures, products which did not contain any changes compared to the last sent version..
     *
     */
    public function testProgressByProcessId()
    {
    }

    /**
     * Test case for succeededByProcessId
     *
     * Request the succeeded products of the product data delivery with the linked processUuid. The response will contain a list of successfully delivered products..
     *
     */
    public function testSucceededByProcessId()
    {
    }

    /**
     * Test case for unchangedByProcessId
     *
     * Request the unchanged products of the product data delivery with the linked processUuid. The response will contain a list of unchanged products..
     *
     */
    public function testUnchangedByProcessId()
    {
    }
}
