<?php
/**
 * ReturnsStatusApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Returns Status Info API
 *
 * Returns Interface
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Otto\Client;

use Otto\Client\Configuration;
use Otto\Client\ApiException;
use Otto\Client\ObjectSerializer;

/**
 * ReturnsStatusApiTest Class Doc Comment
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnsStatusApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getPositionItemsForUsingGET
     *
     * Get all the items filtered on return status.
     *
     */
    public function testGetPositionItemsForUsingGET()
    {
    }

    /**
     * Test case for receiveAcceptedReturnsV2UsingPOST
     *
     * Accept the return for a sent position item (up to 200 items per request).
     *
     */
    public function testReceiveAcceptedReturnsV2UsingPOST()
    {
    }

    /**
     * Test case for receiveRejectedReturnsV2UsingPOST
     *
     * Reject the return for a sent position item (up to 200 items per request).
     *
     */
    public function testReceiveRejectedReturnsV2UsingPOST()
    {
    }
}
