<?php
/**
 * ShipmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shipments
 *
 * This interface describes all endpoints regarding the shipment domain.
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Otto\Client;

use Otto\Client\Configuration;
use Otto\Client\ApiException;
use Otto\Client\ObjectSerializer;

/**
 * ShipmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Otto\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShipmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appendPositionItemsByCarrierAndTrackingNumberUsingPOST
     *
     * .
     *
     */
    public function testAppendPositionItemsByCarrierAndTrackingNumberUsingPOST()
    {
    }

    /**
     * Test case for appendPositionItemsUsingPOST
     *
     * .
     *
     */
    public function testAppendPositionItemsUsingPOST()
    {
    }

    /**
     * Test case for createdAndSentShipmentUsingPOST
     *
     * .
     *
     */
    public function testCreatedAndSentShipmentUsingPOST()
    {
    }

    /**
     * Test case for listShipmentsUsingGET
     *
     * .
     *
     */
    public function testListShipmentsUsingGET()
    {
    }

    /**
     * Test case for shipmentByCarrierAndTrackingNumberUsingGET
     *
     * .
     *
     */
    public function testShipmentByCarrierAndTrackingNumberUsingGET()
    {
    }

    /**
     * Test case for shipmentUsingGET
     *
     * .
     *
     */
    public function testShipmentUsingGET()
    {
    }
}
